[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sevens_token = "Ah4sw8i5k74TC7tCzSrqkEitNdQVRhgrPsKfUrhqzEbn"
sevens_token_management = "DLNR4oQQajCa6UyATqUzpqJgguUCkg3hShZPTMsVKq3h"

[workspace]
members = [
    "contracts/sevens-token",
    "contracts/sevens-token-management",
]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"